// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frueepczgcscprzaapvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZydWVlcGN6Z2NzY3ByemFhcHZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NzU1MDQsImV4cCI6MjA2MDE1MTUwNH0.GUfKDv5NCIfP7kFFLb1sJuwIDfz3-IGjIHBwPf9_QB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);